version: '{build}'
os: Visual Studio 2022
branches:
  only:
  - master
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_commits:
  files:
    - LICENSE
before_build:
  - cmd: dotnet --version
build_script:
- ps: dotnet build Savorboard.CAP.InMemoryMessageQueue.sln
- ps: dotnet pack ./src/Savorboard.CAP.InMemoryMessageQueue/Savorboard.CAP.InMemoryMessageQueue.csproj -o artifacts/packages
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: sqSgfuOl/CQhAn9TL+PzKRkxAZ9Eoql1ghXU4K0LBOXUdtjAMHgXz4itALPYtwn6
  skip_symbols: false
  artifact: /artifacts\/packages\/.+\.(s?)nupkg