version: '{build}'
os: Visual Studio 2022
branches:
  only:
  - master
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_commits:
  files:
    - LICENSE
build_script:
- ps: dotnet build Savorboard.CAP.InMemoryMessageQueue.sln
test: off
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
  provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
    secure: hZmhgcYCuVBJzPljwysslhumZnIlR+Y1FdlT6+XsfHvTXwUzAeCAurcppZ4cKNTz
  skip_symbols: false
  artifact: /artifacts\/packages\/.+\.nupkg/